// frontend/src/pages/angular/admin-dashboard/admin-dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { trigger, transition, style, animate } from '@angular/animations';

interface Product {
    id: number;
    name: string;
    farmer_name: string;
    base_price: number;
    final_price: number;
    image?: string;
}

interface Stats {
    total_savings: number;
    total_farmers: number;
    total_buyers: number;
    total_revenue: number;
    recent_activity: { detail: string; date: string }[];
}

@Component({
    selector: 'app-admin-dashboard',
    templateUrl: './admin-dashboard.component.html',
    styleUrls: ['./admin-dashboard.component.css'],
    animations: [
        trigger('fadeIn', [
            transition(':enter', [
                style({ opacity: 0, transform: 'translateY(10px)' }),
                animate('300ms ease-out', style({ opacity: 1, transform: 'translateY(0)' })),
            ]),
            transition(':leave', [
                animate('200ms ease-in', style({ opacity: 0, transform: 'scale(0.95)' })),
            ]),
        ]),
    ],
})
export class AdminDashboardComponent implements OnInit {
    pendingProducts: Product[] = [];
    stats: Stats | null = null;
    activeTab: 'moderation' | 'activity' = 'moderation';
    loading = false;
    token = localStorage.getItem('token');

    constructor(private http: HttpClient) { }

    ngOnInit(): void {
        this.fetchData();
    }

    fetchData(): void {
        if (!this.token) {
            console.error('No token found');
            return;
        }

        const headers = new HttpHeaders({ Authorization: `Bearer ${this.token}` });

        // Using forkJoin would be better in a real app, but keep it simple for now
        this.http.get<Product[]>('http://localhost:5000/api/admin/pending-products', { headers })
            .subscribe({
                next: (data) => this.pendingProducts = data,
                error: () => console.error('Failed to fetch pending products')
            });

        this.http.get<Stats>('http://localhost:5000/api/admin/stats', { headers })
            .subscribe({
                next: (data) => this.stats = data,
                error: () => console.error('Failed to fetch stats')
            });
    }

    handleAction(productId: number, action: string): void {
        const headers = new HttpHeaders({ Authorization: `Bearer ${this.token}` });
        this.http.post('http://localhost:5000/api/admin/product-action',
            { product_id: productId, action },
            { headers }
        ).subscribe({
            next: () => this.fetchData(),
            error: () => alert('Action failed')
        });
    }

    setActiveTab(tab: 'moderation' | 'activity'): void {
        this.activeTab = tab;
    }
}

<div class="max-w-6xl mx-auto px-6 font-['Outfit']" *ngIf="stats; else loadingTpl">

    <!-- Header -->
    <div class="flex flex-col md:flex-row justify-between items-start md:items-center mb-10 gap-4">
        <div>
            <h1 class="text-3xl font-black text-slate-800 italic tracking-tight">MEDIATOR CONTROL PANEL</h1>
            <p class="text-gray-500 font-medium">Overseeing agricultural trade & logistics</p>
        </div>

        <div class="flex bg-gray-100 p-1.5 rounded-2xl ring-1 ring-gray-200">
            <button (click)="setActiveTab('moderation')"
                [class]="activeTab === 'moderation' ? 'bg-white shadow-xl text-primary-600' : 'text-gray-500 hover:text-gray-700'"
                class="px-6 py-2.5 rounded-xl transition-all font-black text-xs tracking-widest">
                MODERATION
            </button>
            <button (click)="setActiveTab('activity')"
                [class]="activeTab === 'activity' ? 'bg-white shadow-xl text-primary-600' : 'text-gray-500 hover:text-gray-700'"
                class="px-6 py-2.5 rounded-xl transition-all font-black text-xs tracking-widest">
                GLOBAL ACTIVITY
            </button>
        </div>
    </div>

    <!-- Stats Overview -->
    <div class="grid grid-cols-1 md:grid-cols-4 gap-6 mb-12">
        <!-- Admin Savings -->
        <div class="card !bg-slate-900 border-none group p-6 rounded-2xl relative overflow-hidden">
            <!-- Icon Placeholder (Lucide icons need a component or SVG) -->
            <div class="text-primary-400 mb-4 group-hover:scale-110 transition-transform">
                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <polyline points="23 6 13.5 15.5 8.5 10.5 1 18"></polyline>
                    <polyline points="17 6 23 6 23 12"></polyline>
                </svg>
            </div>
            <p class="text-[10px] font-black text-slate-400 uppercase tracking-widest">Admin Savings</p>
            <p class="text-3xl font-black text-white italic">₹{{ stats.total_savings | number }}</p>
            <p class="text-[10px] text-primary-400 font-bold mt-1">LOGISTICS FEE (₹5/KG)</p>
        </div>

        <!-- Trade Network -->
        <div class="card bg-white p-6 rounded-2xl border border-slate-100 shadow-sm">
            <div class="text-blue-500 mb-4">
                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                    <circle cx="9" cy="7" r="4"></circle>
                    <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                    <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                </svg>
            </div>
            <p class="text-[10px] font-black text-gray-400 uppercase tracking-widest">Trade Network</p>
            <p class="text-2xl font-black text-slate-800 italic">{{ stats.total_farmers }} Farmers · {{
                stats.total_buyers }} Buyers</p>
        </div>

        <!-- Total Volume -->
        <div class="card bg-white p-6 rounded-2xl border border-slate-100 shadow-sm">
            <div class="text-orange-500 mb-4">
                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"></path>
                    <line x1="3" y1="6" x2="21" y2="6"></line>
                    <path d="M16 10a4 4 0 0 1-8 0"></path>
                </svg>
            </div>
            <p class="text-[10px] font-black text-gray-400 uppercase tracking-widest">Total Volume</p>
            <p class="text-2xl font-black text-slate-800 italic">₹{{ stats.total_revenue | number }}</p>
        </div>

        <!-- Pending Verification -->
        <div class="card bg-white p-6 rounded-2xl border border-slate-100 shadow-sm">
            <div class="text-purple-500 mb-4">
                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <circle cx="12" cy="12" r="10"></circle>
                    <polyline points="12 6 12 12 16 14"></polyline>
                </svg>
            </div>
            <p class="text-[10px] font-black text-gray-400 uppercase tracking-widest">Pending Verification</p>
            <p class="text-2xl font-black text-slate-800 italic">{{ pendingProducts.length }}</p>
        </div>
    </div>

    <!-- Content Area -->
    <div [ngSwitch]="activeTab">

        <!-- Moderation Tab -->
        <div *ngSwitchCase="'moderation'">
            <h2 class="text-xl font-black text-slate-800 mb-6 flex items-center gap-2">
                <svg class="text-primary-600" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                    viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                    stroke-linejoin="round">
                    <line x1="16.5" y1="9.4" x2="7.5" y2="4.21"></line>
                    <path
                        d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z">
                    </path>
                    <polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline>
                    <line x1="12" y1="22.08" x2="12" y2="12"></line>
                </svg>
                CROP VERIFICATION QUEUE
            </h2>

            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                <div *ngFor="let p of pendingProducts" @fadeIn
                    class="card p-0 overflow-hidden group bg-white rounded-2xl border border-slate-100 shadow-sm">
                    <div class="h-56 bg-gray-100 relative">
                        <ng-container *ngIf="p.image; else noImage">
                            <img [src]="'http://localhost:5000' + p.image" class="w-full h-full object-cover" />
                        </ng-container>
                        <ng-template #noImage>
                            <div class="w-full h-full flex items-center justify-center text-gray-300 italic">No
                                Reference Photo</div>
                        </ng-template>

                        <div class="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent flex items-end p-6">
                            <div class="text-white">
                                <p class="text-[10px] font-black uppercase tracking-widest opacity-80">Farmer: {{
                                    p.farmer_name }}</p>
                                <h3 class="text-2xl font-black italic">{{ p.name }}</h3>
                            </div>
                        </div>
                    </div>

                    <div class="p-6">
                        <div class="flex justify-between items-center mb-6">
                            <div>
                                <p class="text-[10px] font-black text-gray-400 uppercase tracking-widest">Farmer Base
                                </p>
                                <p class="text-xl font-bold text-slate-700">₹{{ p.base_price }}/kg</p>
                            </div>
                            <div class="h-8 w-[1px] bg-gray-100 rotate-12"></div>
                            <div class="text-right">
                                <p class="text-[10px] font-black text-primary-600 uppercase tracking-widest">Buyer Final
                                </p>
                                <p class="text-2xl font-black text-primary-700 italic">₹{{ p.final_price }}/kg</p>
                            </div>
                        </div>

                        <div class="flex gap-3">
                            <button (click)="handleAction(p.id, 'refused')"
                                class="flex-1 py-3 rounded-xl border-2 border-red-50 text-red-500 font-black text-xs uppercase tracking-widest flex items-center justify-center gap-2 hover:bg-red-50 transition-all">
                                <!-- XCircle Icon -->
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round">
                                    <circle cx="12" cy="12" r="10"></circle>
                                    <line x1="15" y1="9" x2="9" y2="15"></line>
                                    <line x1="9" y1="9" x2="15" y2="15"></line>
                                </svg>
                                Refuse
                            </button>
                            <button (click)="handleAction(p.id, 'approved')"
                                class="flex-1 bg-primary-600 text-white rounded-xl font-black text-xs uppercase tracking-widest flex items-center justify-center gap-2 hover:shadow-xl hover:shadow-primary-100 transition-all">
                                <!-- ShieldCheck Icon -->
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round">
                                    <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
                                    <polyline points="9 12 11 14 15 10"></polyline>
                                </svg>
                                Approve
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <div *ngIf="pendingProducts.length === 0"
                class="p-32 text-center card bg-gray-50/50 border-dashed border-2 rounded-2xl">
                <div class="mx-auto text-gray-200 mb-4 inline-block">
                    <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
                        <polyline points="9 12 11 14 15 10"></polyline>
                    </svg>
                </div>
                <p class="text-gray-400 font-bold uppercase tracking-widest italic">Verification queue is clear</p>
            </div>
        </div>

        <!-- Activity Tab -->
        <div *ngSwitchCase="'activity'">
            <div class="card !p-0 overflow-hidden bg-white rounded-2xl border border-slate-100 shadow-sm">
                <div class="px-8 py-6 border-b border-gray-100 bg-gray-50/50">
                    <h2 class="text-xl font-black text-slate-800 flex items-center gap-2 italic">
                        LIVE NETWORK FEED
                    </h2>
                </div>
                <div class="p-4">
                    <div *ngFor="let act of stats.recent_activity"
                        class="flex items-center gap-4 p-4 hover:bg-gray-50 rounded-2xl transition-all">
                        <div
                            class="w-12 h-12 rounded-xl bg-primary-100 flex items-center justify-center text-primary-600">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"
                                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round">
                                <path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"></path>
                                <line x1="3" y1="6" x2="21" y2="6"></line>
                                <path d="M16 10a4 4 0 0 1-8 0"></path>
                            </svg>
                        </div>
                        <div class="flex-1">
                            <p class="font-bold text-slate-800">{{ act.detail }}</p>
                            <p class="text-[10px] font-black text-gray-400 uppercase tracking-widest">{{ act.date }}</p>
                        </div>
                        <div class="text-right">
                            <p class="text-sm font-black text-primary-600">+₹5.00 Logistics</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<ng-template #loadingTpl>
    <div class="flex items-center justify-center h-screen">Loading Mediator Control Panel...</div>
</ng-template>

// frontend/src/pages/AdminDashboard.jsx
import { useState, useEffect } from 'react';
import axios from 'axios';
import { ShieldCheck, XCircle, TrendingUp, Users, Package, ShoppingBag, Clock } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

const AdminDashboard = () => {
    const [pendingProducts, setPendingProducts] = useState([]);
    const [stats, setStats] = useState(null);
    const [activeTab, setActiveTab] = useState('moderation');
    const [loading, setLoading] = useState(false);

    const token = localStorage.getItem('token');

    useEffect(() => {
        fetchData();
    }, []);

    const fetchData = async () => {
        try {
            const [productsRes, statsRes] = await Promise.all([
                axios.get('http://localhost:5000/api/admin/pending-products', { headers: { Authorization: `Bearer ${token}` } }),
                axios.get('http://localhost:5000/api/admin/stats', { headers: { Authorization: `Bearer ${token}` } })
            ]);
            setPendingProducts(productsRes.data);
            setStats(statsRes.data);
        } catch (err) {
            console.error('Failed to fetch admin data');
        }
    };

    const handleAction = async (productId, action) => {
        try {
            await axios.post('http://localhost:5000/api/admin/product-action',
                { product_id: productId, action },
                { headers: { Authorization: `Bearer ${token}` } }
            );
            fetchData();
        } catch (err) {
            alert('Action failed');
        }
    };

    if (!stats) return <div className="flex items-center justify-center h-screen">Loading Mediator Control Panel...</div>;

    return (
        <div className="max-w-6xl mx-auto px-6">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-10 gap-4">
                <div>
                    <h1 className="text-3xl font-black text-slate-800 font-['Outfit'] italic tracking-tight">MEDIATOR CONTROL PANEL</h1>
                    <p className="text-gray-500 font-medium">Overseeing agricultural trade & logistics</p>
                </div>

                <div className="flex bg-gray-100 p-1.5 rounded-2xl ring-1 ring-gray-200">
                    <button
                        onClick={() => setActiveTab('moderation')}
                        className={`px-6 py-2.5 rounded-xl transition-all font-black text-xs tracking-widest ${activeTab === 'moderation' ? 'bg-white shadow-xl text-primary-600' : 'text-gray-500 hover:text-gray-700'}`}
                    >
                        MODERATION
                    </button>
                    <button
                        onClick={() => setActiveTab('activity')}
                        className={`px-6 py-2.5 rounded-xl transition-all font-black text-xs tracking-widest ${activeTab === 'activity' ? 'bg-white shadow-xl text-primary-600' : 'text-gray-500 hover:text-gray-700'}`}
                    >
                        GLOBAL ACTIVITY
                    </button>
                </div>
            </div>

            {/* Stats Overview */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-12">
                <div className="card !bg-slate-900 border-none group">
                    <TrendingUp className="text-primary-400 mb-4 group-hover:scale-110 transition-transform" size={28} />
                    <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Admin Savings</p>
                    <p className="text-3xl font-black text-white font-['Outfit'] italic">₹{stats.total_savings.toLocaleString()}</p>
                    <p className="text-[10px] text-primary-400 font-bold mt-1">LOGISTICS FEE (₹5/KG)</p>
                </div>
                <div className="card">
                    <Users className="text-blue-500 mb-4" size={28} />
                    <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Trade Network</p>
                    <p className="text-2xl font-black text-slate-800 font-['Outfit'] italic">{stats.total_farmers} Farmers · {stats.total_buyers} Buyers</p>
                </div>
                <div className="card">
                    <ShoppingBag className="text-orange-500 mb-4" size={28} />
                    <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Total Volume</p>
                    <p className="text-2xl font-black text-slate-800 font-['Outfit'] italic">₹{stats.total_revenue.toLocaleString()}</p>
                </div>
                <div className="card">
                    <Clock className="text-purple-500 mb-4" size={28} />
                    <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Pending Verification</p>
                    <p className="text-2xl font-black text-slate-800 font-['Outfit'] italic">{pendingProducts.length}</p>
                </div>
            </div>

            {activeTab === 'moderation' ? (
                <div>
                    <h2 className="text-xl font-black text-slate-800 mb-6 flex items-center gap-2">
                        <Package className="text-primary-600" /> CROP VERIFICATION QUEUE
                    </h2>

                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {pendingProducts.map(p => (
                            <motion.div layout key={p.id} className="card p-0 overflow-hidden group">
                                <div className="h-56 bg-gray-100 relative">
                                    {p.image ? (
                                        <img src={`http://localhost:5000${p.image}`} className="w-full h-full object-cover" />
                                    ) : (
                                        <div className="w-full h-full flex items-center justify-center text-gray-300 italic">No Reference Photo</div>
                                    )}
                                    <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent flex items-end p-6">
                                        <div className="text-white">
                                            <p className="text-[10px] font-black uppercase tracking-widest opacity-80">Farmer: {p.farmer_name}</p>
                                            <h3 className="text-2xl font-black italic">{p.name}</h3>
                                        </div>
                                    </div>
                                </div>
                                <div className="p-6">
                                    <div className="flex justify-between items-center mb-6">
                                        <div>
                                            <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Farmer Base</p>
                                            <p className="text-xl font-bold text-slate-700">₹{p.base_price}/kg</p>
                                        </div>
                                        <div className="h-8 w-[1px] bg-gray-100 rotate-12"></div>
                                        <div className="text-right">
                                            <p className="text-[10px] font-black text-primary-600 uppercase tracking-widest">Buyer Final</p>
                                            <p className="text-2xl font-black text-primary-700 italic">₹{p.final_price}/kg</p>
                                        </div>
                                    </div>

                                    <div className="flex gap-3">
                                        <button
                                            onClick={() => handleAction(p.id, 'refused')}
                                            className="flex-1 py-3 rounded-xl border-2 border-red-50 text-red-500 font-black text-xs uppercase tracking-widest flex items-center justify-center gap-2 hover:bg-red-50 transition-all"
                                        >
                                            <XCircle size={16} /> Refuse
                                        </button>
                                        <button
                                            onClick={() => handleAction(p.id, 'approved')}
                                            className="flex-1 bg-primary-600 text-white rounded-xl font-black text-xs uppercase tracking-widest flex items-center justify-center gap-2 hover:shadow-xl hover:shadow-primary-100 transition-all"
                                        >
                                            <ShieldCheck size={16} /> Approve
                                        </button>
                                    </div>
                                </div>
                            </motion.div>
                        ))}
                    </div>
                    {pendingProducts.length === 0 && (
                        <div className="p-32 text-center card bg-gray-50/50 border-dashed border-2">
                            <ShieldCheck className="mx-auto text-gray-200 mb-4" size={64} />
                            <p className="text-gray-400 font-bold uppercase tracking-widest italic">Verification queue is clear</p>
                        </div>
                    )}
                </div>
            ) : (
                <div className="card !p-0 overflow-hidden">
                    <div className="px-8 py-6 border-b border-gray-100 bg-gray-50/50">
                        <h2 className="text-xl font-black text-slate-800 flex items-center gap-2 italic">
                            LIVE NETWORK FEED
                        </h2>
                    </div>
                    <div className="p-4">
                        {stats.recent_activity.map((act, idx) => (
                            <div key={idx} className="flex items-center gap-4 p-4 hover:bg-gray-50 rounded-2xl transition-all">
                                <div className={`w-12 h-12 rounded-xl flex items-center justify-center ${act.type === 'order' ? 'bg-primary-100 text-primary-600' : 'bg-blue-100 text-blue-600'}`}>
                                    {act.type === 'order' ? <ShoppingBag size={20} /> : <Package size={20} />}
                                </div>
                                <div className="flex-1">
                                    <p className="font-bold text-slate-800">{act.detail}</p>
                                    <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">{act.date}</p>
                                </div>
                                <div className="text-right">
                                    <p className={`text-sm font-black ${act.type === 'order' ? 'text-primary-600' : 'text-blue-500'}`}>{act.amount}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            )}
        </div>
    );
};

export default AdminDashboard;
